//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Common.Database.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbDotNet.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start transaction on this connection. .
        /// </summary>
        internal static string SYSTEM_ERROR_FAILED_TO_BEGIN_TRANSACTION {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_FAILED_TO_BEGIN_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to bulkcopy table {0}.
        /// </summary>
        internal static string SYSTEM_ERROR_FAILED_TO_BULKCOPY {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_FAILED_TO_BULKCOPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to commit transaction..
        /// </summary>
        internal static string SYSTEM_ERROR_FAILED_TO_COMMIT_TRANSACTION {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_FAILED_TO_COMMIT_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute command.All changes has been rolled back.
        /// </summary>
        internal static string SYSTEM_ERROR_FAILED_TO_EXECUTE_COMMAND {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_FAILED_TO_EXECUTE_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize connection.Please check that you have provided a valid connectionstring({0}) .
        /// </summary>
        internal static string SYSTEM_ERROR_FAILED_TO_INITIALIZE {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_FAILED_TO_INITIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open a connection using connectionstring: &apos;{0}&apos;.
        /// </summary>
        internal static string SYSTEM_ERROR_FAILED_TO_OPEN_CONNECTION {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_FAILED_TO_OPEN_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rollback transaction..
        /// </summary>
        internal static string SYSTEM_ERROR_FAILED_TO_ROLLBACK_TRANSACTION {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_FAILED_TO_ROLLBACK_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save table {0}. Make sure that the table has been filled with its schema or that the datatable has been given a name corresponding to the database table.
        /// </summary>
        internal static string SYSTEM_ERROR_FAILED_TO_SAVE_TABLE {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_FAILED_TO_SAVE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to select distinct rows from datatable &apos;{0}&apos;.
        /// </summary>
        internal static string SYSTEM_ERROR_FAILED_TO_SELECTDISTINCT {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_FAILED_TO_SELECTDISTINCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the value for parameter {0}. Stored procedure {1} contains only this parameters {2}.
        /// </summary>
        internal static string SYSTEM_ERROR_INVALID_PARAMETERNAME {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR_INVALID_PARAMETERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find procedure {0}. Make sure that the name is spelled correctly..
        /// </summary>
        internal static string SYSTEM_UNABLE_TO_FIND_PROCEDURE {
            get {
                return ResourceManager.GetString("SYSTEM_UNABLE_TO_FIND_PROCEDURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start more transactions on this connection. This connection is already in a transaction and must be committed or rolled back before a new transaction can be started..
        /// </summary>
        internal static string USER_ERROR_FAILED_TO_BEGIN_TRANSACTION {
            get {
                return ResourceManager.GetString("USER_ERROR_FAILED_TO_BEGIN_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot commit a transaction unless the connection is in a transaction.
        /// </summary>
        internal static string USER_ERROR_FAILED_TO_COMMIT_TRANSACTION {
            get {
                return ResourceManager.GetString("USER_ERROR_FAILED_TO_COMMIT_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rollback a transaction unless the connection is in a transaction. Make sure there is a corresponding call to BeginTransaction()..
        /// </summary>
        internal static string USER_ERROR_FAILED_TO_ROLLBACK_TRANSACTION {
            get {
                return ResourceManager.GetString("USER_ERROR_FAILED_TO_ROLLBACK_TRANSACTION", resourceCulture);
            }
        }
    }
}
